ФИО:<ins>(Перевощиков Андрей)</ins>     группа: <ins>(2)</ins>

## Работа с массивами в библиотеке NumPy

In [114]:
import numpy as np
from random import random, randint
'''university programming '''

 <b>Задание 1.</b> Задать матрицу $A_{4\times 4}$ случайных чисел любого типа.

In [115]:
f = lambda i, j: ((i * random() + j * random() + random()) * 10)
# f = lambda i, j: (i + j + 1) * random() * 10 + (i - j) * random() * 10
# f = lambda i  , j : 10 - (i + 2 + j)
# A = np.array(np.empty(4, dtype = np.float32))
# np.empty(4, dtype = np.float32)
A = np.fromfunction(f, (4, 4))

print(A)
# print(np.linalg.det(A))

[[ 0.2600371   5.87085385 11.48167061 17.09248736]
 [ 3.31310589  8.92392265 14.5347394  20.14555615]
 [ 6.36617469 11.97699144 17.5878082  23.19862495]
 [ 9.41924348 15.03006024 20.64087699 26.25169374]]


 <b>Задание 2.</b> Случайным образом сгенерировать два целых числа $k$, $l$. Найти минор $M_{k,l}$. 
 
 <ins>Указание:</ins> Минором $M_{k,l} $ матрицы  называется определитель матрицы, полученной путём вычеркивания $k$-столбца и $l$-строки
 


In [116]:
def get_minor(mat: np.ndarray, k: int, l: int) -> np.ndarray:
    return np.delete(np.delete(mat, l, axis=0), k, axis=1)


def get_det_by_minor(mat: np.ndarray, k: int, l: int):
    return np.linalg.det(get_minor(mat, k, l))

# print(get_minor(A, 1, 2))
# print(get_det(get_minor(A, 2, 2)))
# k , l =

<b>Задание 3.</b> Используя код задания 2, вычислить определитель исходной матрицы $A$ путём разложения её по произвольным строке или столбцу. 

In [117]:
# print(dir(A))
mtest = [[-4, -2, -7, 8], [2, 7, 4, 9], [2, 0, 6, -3], [6, 4, -10, -4]]
mtest = np.array(mtest)


def get_det_task(mat: np.ndarray) -> float:
    res = 0
    z = 1
    for i in range(len(A)):
        # print(mat[0][i])
        # print(get_minor(mat , i , 0))
        res += mat[0][i] * get_det_by_minor(mat, i, 0) * z
        z *= -1
        # print(get_minor(A, i, 0))

    return res


print(f"Встроенная функиця {np.linalg.det(mtest)}")
print(f"Моя функиця {get_det_task(mtest)}")
print(get_det_task(A))

Встроенная функиця -1926.0000000000007
Моя функиця -1926.0000000000018
-1.4942412452888105e-13


<b>Задание 4.</b> Задать массив целых чисел $x$ случайной размерности $d > 2$. Случайным образом определить целое число $n$. Определить сколько и какие элементы в массиве $x$ имеют ту же четность и тот же знак, что и заданное число $n$. 

In [118]:
def generate_array_int() -> np.ndarray:
    n = randint(2, 10)
    return np.array([randint(-10, 10) for _ in range(n)])


def count_of_same(arr: np.ndarray, n: int):
    res = 0
    # mask = all([(arr %2 == n%2) , (arr*n>=0)])
    # print(mask)
    # print(arr[mask])
    t = arr[np.where((arr % 2 == n % 2) & (arr * n >= 0))]
    return len(t), t


# print(np.random.random_integers(-10, 10, randint(2, 10)))
# print(generate_array_int())
arr = np.random.random_integers(-10, 10 + 1, randint(2, 10))
n = arr[0]
print(f'Elements like {n} in arr {arr} : {count_of_same(arr, n)[0]} , this elemen is {count_of_same(arr, n)[1]}')



Elements like 9 in arr [  9 -10  -3   9  -2   9  11  11] : 5 , this elemen is [ 9  9  9 11 11]


C:\Users\rasha\AppData\Local\Temp/ipykernel_14964/1199424354.py:17: DeprecationWarning: This function is deprecated. Please call randint(-10, 11 + 1) instead
  arr = np.random.random_integers(-10, 10 + 1, randint(2, 10))


<b>Задание 5.</b> Задать два массива вещественных чисел $x$ и $y$ случайной размерности $d > 2$.Получить новый массив $z$, содержащий на $i$-месте целую часть $x_i$, если его дробная часть оказалась больше, чем дробная часть $y_i$ и наоборот. 

Пример входных данных и результата работы программы:

x = [15.14903699  3.77044949 -7.36159982  8.80036869  6.10691581]

y = [ -8.65563977 -12.60192654  15.90580188 -16.63450346  11.83626016]

z = [ -8. 3.  15. 8.  11.]


In [119]:
n = randint(2, 10)

x = (10 - (-10)) * np.random.rand(n) - 10
y = (10 - (-10)) * np.random.rand(n) - 10
z = np.array([])
print(f' x = {x} \n y = {y}')

func = lambda  x , y : int (x ) if abs(x)%1 > abs(y)%1 else int(y)
print(func( 1.1 , 2.01))
for i in range(n):
    # print(func(x[i] , y[i]))
    z = np.append(z , func(x[i] , y[i]))
    # print(z)
print(f'z = {z}' )

 x = [ 7.98590619  7.96530204 -7.84756095 -4.14704963  3.99423123 -7.9134258
  6.43125723  9.42480003 -7.61738597  7.36378861] 
 y = [ 7.3111664   4.33850758  7.71794892  7.49915764 -4.48134031  1.14249942
  5.15399305  2.65464733 -0.28607402 -0.34135777]
1
z = [ 7.  7. -7.  7.  3. -7.  6.  2. -7.  7.]


<b>Задание 6.</b> Задать массив натуральных чисел $x$ случайной размерности $d > 2$. Получить массив $y$, содержащий только те элементы из $x$, которые являются степенями двойки.

In [120]:
arr = np.array([randint(1, 65) for _ in range(n)])
mask = (arr & (arr-1) == 0)
new_arr = arr[mask]

print(f'x = {arr}  -> y = {new_arr}')


x = [43 14 26 31 24 42 35 48  9 24]  -> y = []
